security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory: { memory: null }
        my_users:
            entity:
                class: 'App\Entity\Users'
                property: 'email'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: 'my_users'
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: app_homepage

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # merci pour le nombre :)

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/seller, roles: ROLE_SELLER }
         - { path: ^/items, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
